version: "3"

services:
  kk67_be:
    build: ./webroot/kk67-backend
    hostname: kk67_be
    container_name: kk67_be
    working_dir: /usr/src/app
    network_mode: "host"
    volumes:
      - ${BE_APP_PATH}:/usr/src/app:rw

  kk67_fe:
    image: node:14
    hostname: kk67_fe
    container_name: kk67_fe
    command: bash -c "yarn install && yarn dev:host"
    environment:
      - NODE_ENV=development
    working_dir: /usr/src/app
    network_mode: "host"
    volumes:
      - ${FE_APP_PATH}:/usr/src/app:rw
