version: "3"

services:
  kk67_be:
    build: ./webroot/kk67-backend
    hostname: kk67_be
    container_name: kk67_be
    working_dir: /usr/src/app
    ports:
      - "5000:5000"
    volumes:
      - ${BE_APP_PATH}:/usr/src/app:rw

  kk67_fe:
    image: node:14
    hostname: kk67_fe
    container_name: kk67_fe
    command: bash -c "yarn install && yarn dev:host"
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "2000:2000"
    working_dir: /usr/src/app
    volumes:
      - ${FE_APP_PATH}:/usr/src/app:rw
  kk67_php:
    build: ./webroot/kk67-backend-php
    hostname: kk67_php
    container_name: kk67_php
    working_dir: /usr/src/app
    env_file:
      - ./webroot/kk67-backend-php/.env
    ports:
      - 4000:4000
    volumes:
      - ${BE_PHP_APP_PATH}:/usr/src/app:rw
